language: python
python:
  - 2.7
before_install:
  - sudo apt-get install python-pip python-dev git
install:
  - pip install --upgrade pip && pip install -r requirements.txt
script:
  - python -u run.py
